### ISSUE TITLE
no implicit conversion of Fixnum into String

### ISSUE THREAD

**Issue by FrankelJb** [karolsluszniak/cloudless-box#1]
Good Day,

I just want to start by saying that this cookbook is fantastic and I have high hopes for being able to use it in my production environment. However, I started getting the exception above and cannot figure out what is causing it.

This is the error message

```
                    Mixlib::ShellOut::ShellCommandFailed
                    ------------------------------------
                    Expected process to exit with [0], but received '1'
                    ---- Begin output of eval "$(rbenv init -)" ----
                    STDOUT:
                    STDERR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:174:in `[]=': no implicit conversion of Fixnum into String (TypeError)
```

I was not getting this error yesterday but has started today for some reason.

Your help will be greatly appreciated.

**Comment by FrankelJb** [comment]
I looked more closely at the issue and it looks like it was being caused by the environment variables that I was setting through `default["cloudless-box"]["applications"]["app_name"]["env"]`. It was caused by using an integer in the Chef attribute file that was then trying to be parsed to a string.

This issue is closed. My apologies

**Comment by karolsluszniak** [comment]
No problem. Glad to hear it may be helpful to others. I'm using it successfully on production and fixing issues on regular basis, but there still may be some rough corners as I haven't received too much feedback from others yet.
